name: Deploy to Dev

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PUBLIC_API: ${{ secrets.PUBLIC_API }}
  PUBLIC_ASTRO_API: ${{ secrets.PUBLIC_ASTRO_API }}

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: Dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and build
        run: |
          cd astro
          npm install -g pm2
          npm install -g pnpm
          pnpm install
          pnpm run build

      - name: Deploy with PM2
        run: |
          cd astro
          # Check if process exists before stopping
          if pm2 list | grep -q "web-client"; then
            pm2 stop web-client
            pm2 delete web-client
          fi
          pm2 start ./dist/server/entry.mjs --name web-client -- --port 4321 --host 0.0.0.0
          pm2 save 
