name: Deploy to Dev

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PUBLIC_API: ${{ secrets.PUBLIC_API }}
  PUBLIC_ASTRO_API: ${{ secrets.PUBLIC_ASTRO_API }}

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: Dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and run Docker container
        run: |
          cd astro
          docker build -t web-client .
          docker stop web-client || true
          docker rm web-client || true
          docker run -d \
            --name web-client \
            --restart unless-stopped \
            -p 4321:4321 \
            -e PUBLIC_API=${{ secrets.PUBLIC_API }} \
            -e PUBLIC_ASTRO_API=${{ secrets.PUBLIC_ASTRO_API }} \
            web-client 